# Generated by Django 4.1.2 on 2022-11-06 09:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onlinecourse', '0002_remove_question_choice_set_choice_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Ngày giờ được tạo, không thể sửa đổi'),
        ),
        migrations.AddField(
            model_name='course',
            name='created_date',
            field=models.DateField(default=datetime.date.today, help_text='Ngày chỉnh sửa gần nhất'),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Ngày giờ chỉnh sửa gần nhất'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Ngày giờ được tạo, không thể sửa đổi'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='created_date',
            field=models.DateField(default=datetime.date.today, help_text='Ngày chỉnh sửa gần nhất'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Ngày giờ chỉnh sửa gần nhất'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Ngày giờ được tạo, không thể sửa đổi'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='created_date',
            field=models.DateField(default=datetime.date.today, help_text='Ngày chỉnh sửa gần nhất'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Ngày giờ chỉnh sửa gần nhất'),
        ),
        migrations.AddField(
            model_name='learner',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Ngày giờ được tạo, không thể sửa đổi'),
        ),
        migrations.AddField(
            model_name='learner',
            name='created_date',
            field=models.DateField(default=datetime.date.today, help_text='Ngày chỉnh sửa gần nhất'),
        ),
        migrations.AddField(
            model_name='learner',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Ngày giờ chỉnh sửa gần nhất'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Ngày giờ được tạo, không thể sửa đổi'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='created_date',
            field=models.DateField(default=datetime.date.today, help_text='Ngày chỉnh sửa gần nhất'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Ngày giờ chỉnh sửa gần nhất'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.course'),
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Ngày giờ được tạo, không thể sửa đổi'),
        ),
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='created_date',
            field=models.DateField(default=datetime.date.today, help_text='Ngày chỉnh sửa gần nhất'),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Ngày giờ chỉnh sửa gần nhất'),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.lesson'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
