# Generated by Django 4.1.2 on 2022-11-06 09:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('onlinecourse', '0003_course_created_at_course_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=datetime.date.today, help_text='Ngày chỉnh sửa gần nhất')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Ngày giờ chỉnh sửa gần nhất')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Ngày giờ được tạo, không thể sửa đổi')),
                ('choices', models.ManyToManyField(to='onlinecourse.choice')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.enrollment')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='%(app_label)s_%(class)s_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
