# Generated by Django 4.1.2 on 2022-11-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0004_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='grade',
            field=models.IntegerField(blank=True, default=80, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
